// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: events.proto

// Package gophertrunk.v1 holds the canonical wire schemas for the
// GopherTrunk control + audio API. Generated Go bindings live under
// `internal/api/pb/v1` once `make proto` is run with protoc and the
// `protoc-gen-go` / `protoc-gen-go-grpc` plugins installed.
//
// The default `make build` does NOT regenerate or require protoc; the
// REST + SSE + WebSocket surfaces in `internal/api` are hand-written
// against the in-package DTOs and serve as the gRPC server's
// request/response shape once the bindings are generated.

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event is the canonical envelope for everything published on the
// internal events bus and bridged out over the streaming API.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event kind. Values match internal/events.Kind constants
	// ("cc.locked", "cc.lost", "grant", "call.start", "call.end",
	// "sdr.attached", "sdr.detached", "error").
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Server-stamped timestamp in RFC 3339 (UTC).
	Timestamp string `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Discriminated payload. Exactly one of these is set per event.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_CcLocked
	//	*Event_CcLost
	//	*Event_Grant
	//	*Event_CallStart
	//	*Event_CallEnd
	//	*Event_SdrStatus
	//	*Event_Error
	Payload       isEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Event) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetCcLocked() *CCLocked {
	if x != nil {
		if x, ok := x.Payload.(*Event_CcLocked); ok {
			return x.CcLocked
		}
	}
	return nil
}

func (x *Event) GetCcLost() *CCLost {
	if x != nil {
		if x, ok := x.Payload.(*Event_CcLost); ok {
			return x.CcLost
		}
	}
	return nil
}

func (x *Event) GetGrant() *Grant {
	if x != nil {
		if x, ok := x.Payload.(*Event_Grant); ok {
			return x.Grant
		}
	}
	return nil
}

func (x *Event) GetCallStart() *CallStart {
	if x != nil {
		if x, ok := x.Payload.(*Event_CallStart); ok {
			return x.CallStart
		}
	}
	return nil
}

func (x *Event) GetCallEnd() *CallEnd {
	if x != nil {
		if x, ok := x.Payload.(*Event_CallEnd); ok {
			return x.CallEnd
		}
	}
	return nil
}

func (x *Event) GetSdrStatus() *SDRStatus {
	if x != nil {
		if x, ok := x.Payload.(*Event_SdrStatus); ok {
			return x.SdrStatus
		}
	}
	return nil
}

func (x *Event) GetError() *ErrorEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_CcLocked struct {
	CcLocked *CCLocked `protobuf:"bytes,10,opt,name=cc_locked,json=ccLocked,proto3,oneof"`
}

type Event_CcLost struct {
	CcLost *CCLost `protobuf:"bytes,11,opt,name=cc_lost,json=ccLost,proto3,oneof"`
}

type Event_Grant struct {
	Grant *Grant `protobuf:"bytes,12,opt,name=grant,proto3,oneof"`
}

type Event_CallStart struct {
	CallStart *CallStart `protobuf:"bytes,13,opt,name=call_start,json=callStart,proto3,oneof"`
}

type Event_CallEnd struct {
	CallEnd *CallEnd `protobuf:"bytes,14,opt,name=call_end,json=callEnd,proto3,oneof"`
}

type Event_SdrStatus struct {
	SdrStatus *SDRStatus `protobuf:"bytes,15,opt,name=sdr_status,json=sdrStatus,proto3,oneof"`
}

type Event_Error struct {
	Error *ErrorEvent `protobuf:"bytes,16,opt,name=error,proto3,oneof"`
}

func (*Event_CcLocked) isEvent_Payload() {}

func (*Event_CcLost) isEvent_Payload() {}

func (*Event_Grant) isEvent_Payload() {}

func (*Event_CallStart) isEvent_Payload() {}

func (*Event_CallEnd) isEvent_Payload() {}

func (*Event_SdrStatus) isEvent_Payload() {}

func (*Event_Error) isEvent_Payload() {}

type CCLocked struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	FrequencyHz uint32                 `protobuf:"varint,1,opt,name=frequency_hz,json=frequencyHz,proto3" json:"frequency_hz,omitempty"`
	// Protocol-specific identifier: P25 NAC, DMR Color Code, NXDN
	// BaudRate, etc. Carried as a key/value bag for extensibility.
	Attrs         map[string]string `protobuf:"bytes,2,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CCLocked) Reset() {
	*x = CCLocked{}
	mi := &file_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCLocked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCLocked) ProtoMessage() {}

func (x *CCLocked) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCLocked.ProtoReflect.Descriptor instead.
func (*CCLocked) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{1}
}

func (x *CCLocked) GetFrequencyHz() uint32 {
	if x != nil {
		return x.FrequencyHz
	}
	return 0
}

func (x *CCLocked) GetAttrs() map[string]string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

type CCLost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrequencyHz   uint32                 `protobuf:"varint,1,opt,name=frequency_hz,json=frequencyHz,proto3" json:"frequency_hz,omitempty"`
	Attrs         map[string]string      `protobuf:"bytes,2,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CCLost) Reset() {
	*x = CCLost{}
	mi := &file_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCLost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCLost) ProtoMessage() {}

func (x *CCLost) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCLost.ProtoReflect.Descriptor instead.
func (*CCLost) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{2}
}

func (x *CCLost) GetFrequencyHz() uint32 {
	if x != nil {
		return x.FrequencyHz
	}
	return 0
}

func (x *CCLost) GetAttrs() map[string]string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

type Grant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	System        string                 `protobuf:"bytes,1,opt,name=system,proto3" json:"system,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"` // "p25" / "dmr" / "nxdn"
	GroupId       uint32                 `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	SourceId      uint32                 `protobuf:"varint,4,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	FrequencyHz   uint32                 `protobuf:"varint,5,opt,name=frequency_hz,json=frequencyHz,proto3" json:"frequency_hz,omitempty"`
	ChannelId     uint32                 `protobuf:"varint,6,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ChannelNumber uint32                 `protobuf:"varint,7,opt,name=channel_number,json=channelNumber,proto3" json:"channel_number,omitempty"`
	Encrypted     bool                   `protobuf:"varint,8,opt,name=encrypted,proto3" json:"encrypted,omitempty"`
	Emergency     bool                   `protobuf:"varint,9,opt,name=emergency,proto3" json:"emergency,omitempty"`
	DataCall      bool                   `protobuf:"varint,10,opt,name=data_call,json=dataCall,proto3" json:"data_call,omitempty"`
	// P25 encryption metadata recovered from the in-call signalling
	// (Phase 1 LDU2 Encryption Sync, Phase 2 MAC EncryptionSync PDU).
	// Meaningful only when encrypted=true; zero for clear calls and
	// for encrypted calls whose ALGID/KID has not landed yet
	// (Phase 1 grants publish before the first LDU2 — the engine
	// backfills the values via KindCallEncryption).
	AlgorithmId   uint32 `protobuf:"varint,11,opt,name=algorithm_id,json=algorithmId,proto3" json:"algorithm_id,omitempty"`
	KeyId         uint32 `protobuf:"varint,12,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Grant) Reset() {
	*x = Grant{}
	mi := &file_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Grant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grant) ProtoMessage() {}

func (x *Grant) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grant.ProtoReflect.Descriptor instead.
func (*Grant) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{3}
}

func (x *Grant) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

func (x *Grant) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Grant) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *Grant) GetSourceId() uint32 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

func (x *Grant) GetFrequencyHz() uint32 {
	if x != nil {
		return x.FrequencyHz
	}
	return 0
}

func (x *Grant) GetChannelId() uint32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *Grant) GetChannelNumber() uint32 {
	if x != nil {
		return x.ChannelNumber
	}
	return 0
}

func (x *Grant) GetEncrypted() bool {
	if x != nil {
		return x.Encrypted
	}
	return false
}

func (x *Grant) GetEmergency() bool {
	if x != nil {
		return x.Emergency
	}
	return false
}

func (x *Grant) GetDataCall() bool {
	if x != nil {
		return x.DataCall
	}
	return false
}

func (x *Grant) GetAlgorithmId() uint32 {
	if x != nil {
		return x.AlgorithmId
	}
	return 0
}

func (x *Grant) GetKeyId() uint32 {
	if x != nil {
		return x.KeyId
	}
	return 0
}

type CallStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grant         *Grant                 `protobuf:"bytes,1,opt,name=grant,proto3" json:"grant,omitempty"`
	Talkgroup     *TalkGroup             `protobuf:"bytes,2,opt,name=talkgroup,proto3" json:"talkgroup,omitempty"` // optional; null if unknown
	DeviceSerial  string                 `protobuf:"bytes,3,opt,name=device_serial,json=deviceSerial,proto3" json:"device_serial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallStart) Reset() {
	*x = CallStart{}
	mi := &file_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallStart) ProtoMessage() {}

func (x *CallStart) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallStart.ProtoReflect.Descriptor instead.
func (*CallStart) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{4}
}

func (x *CallStart) GetGrant() *Grant {
	if x != nil {
		return x.Grant
	}
	return nil
}

func (x *CallStart) GetTalkgroup() *TalkGroup {
	if x != nil {
		return x.Talkgroup
	}
	return nil
}

func (x *CallStart) GetDeviceSerial() string {
	if x != nil {
		return x.DeviceSerial
	}
	return ""
}

type CallEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grant         *Grant                 `protobuf:"bytes,1,opt,name=grant,proto3" json:"grant,omitempty"`
	Talkgroup     *TalkGroup             `protobuf:"bytes,2,opt,name=talkgroup,proto3" json:"talkgroup,omitempty"`
	DeviceSerial  string                 `protobuf:"bytes,3,opt,name=device_serial,json=deviceSerial,proto3" json:"device_serial,omitempty"`
	StartedAt     string                 `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"` // RFC 3339
	EndedAt       string                 `protobuf:"bytes,5,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"` // EndReason.String()
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallEnd) Reset() {
	*x = CallEnd{}
	mi := &file_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallEnd) ProtoMessage() {}

func (x *CallEnd) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallEnd.ProtoReflect.Descriptor instead.
func (*CallEnd) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{5}
}

func (x *CallEnd) GetGrant() *Grant {
	if x != nil {
		return x.Grant
	}
	return nil
}

func (x *CallEnd) GetTalkgroup() *TalkGroup {
	if x != nil {
		return x.Talkgroup
	}
	return nil
}

func (x *CallEnd) GetDeviceSerial() string {
	if x != nil {
		return x.DeviceSerial
	}
	return ""
}

func (x *CallEnd) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *CallEnd) GetEndedAt() string {
	if x != nil {
		return x.EndedAt
	}
	return ""
}

func (x *CallEnd) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SDRStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Serial        string                 `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"` // "control" / "voice" / "auto"
	Attached      bool                   `protobuf:"varint,4,opt,name=attached,proto3" json:"attached,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SDRStatus) Reset() {
	*x = SDRStatus{}
	mi := &file_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SDRStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SDRStatus) ProtoMessage() {}

func (x *SDRStatus) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SDRStatus.ProtoReflect.Descriptor instead.
func (*SDRStatus) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{6}
}

func (x *SDRStatus) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *SDRStatus) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *SDRStatus) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *SDRStatus) GetAttached() bool {
	if x != nil {
		return x.Attached
	}
	return false
}

type ErrorEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"` // subsystem ("sdr", "p25", "trunking", ...)
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorEvent) Reset() {
	*x = ErrorEvent{}
	mi := &file_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorEvent) ProtoMessage() {}

func (x *ErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorEvent.ProtoReflect.Descriptor instead.
func (*ErrorEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{7}
}

func (x *ErrorEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ErrorEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// TalkGroup mirrors trunking.TalkGroup. Used in CallStart/CallEnd
// envelopes and as the row type for ListTalkgroups responses.
type TalkGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AlphaTag      string                 `protobuf:"bytes,2,opt,name=alpha_tag,json=alphaTag,proto3" json:"alpha_tag,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Tag           string                 `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	Group         string                 `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty"`
	Mode          string                 `protobuf:"bytes,6,opt,name=mode,proto3" json:"mode,omitempty"`
	Priority      int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	Lockout       bool                   `protobuf:"varint,8,opt,name=lockout,proto3" json:"lockout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TalkGroup) Reset() {
	*x = TalkGroup{}
	mi := &file_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TalkGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TalkGroup) ProtoMessage() {}

func (x *TalkGroup) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TalkGroup.ProtoReflect.Descriptor instead.
func (*TalkGroup) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{8}
}

func (x *TalkGroup) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TalkGroup) GetAlphaTag() string {
	if x != nil {
		return x.AlphaTag
	}
	return ""
}

func (x *TalkGroup) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TalkGroup) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *TalkGroup) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *TalkGroup) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *TalkGroup) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *TalkGroup) GetLockout() bool {
	if x != nil {
		return x.Lockout
	}
	return false
}

var File_events_proto protoreflect.FileDescriptor

const file_events_proto_rawDesc = "" +
	"\n" +
	"\fevents.proto\x12\x0egophertrunk.v1\"\xc1\x03\n" +
	"\x05Event\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x127\n" +
	"\tcc_locked\x18\n" +
	" \x01(\v2\x18.gophertrunk.v1.CCLockedH\x00R\bccLocked\x121\n" +
	"\acc_lost\x18\v \x01(\v2\x16.gophertrunk.v1.CCLostH\x00R\x06ccLost\x12-\n" +
	"\x05grant\x18\f \x01(\v2\x15.gophertrunk.v1.GrantH\x00R\x05grant\x12:\n" +
	"\n" +
	"call_start\x18\r \x01(\v2\x19.gophertrunk.v1.CallStartH\x00R\tcallStart\x124\n" +
	"\bcall_end\x18\x0e \x01(\v2\x17.gophertrunk.v1.CallEndH\x00R\acallEnd\x12:\n" +
	"\n" +
	"sdr_status\x18\x0f \x01(\v2\x19.gophertrunk.v1.SDRStatusH\x00R\tsdrStatus\x122\n" +
	"\x05error\x18\x10 \x01(\v2\x1a.gophertrunk.v1.ErrorEventH\x00R\x05errorB\t\n" +
	"\apayload\"\xa2\x01\n" +
	"\bCCLocked\x12!\n" +
	"\ffrequency_hz\x18\x01 \x01(\rR\vfrequencyHz\x129\n" +
	"\x05attrs\x18\x02 \x03(\v2#.gophertrunk.v1.CCLocked.AttrsEntryR\x05attrs\x1a8\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9e\x01\n" +
	"\x06CCLost\x12!\n" +
	"\ffrequency_hz\x18\x01 \x01(\rR\vfrequencyHz\x127\n" +
	"\x05attrs\x18\x02 \x03(\v2!.gophertrunk.v1.CCLost.AttrsEntryR\x05attrs\x1a8\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xef\x02\n" +
	"\x05Grant\x12\x16\n" +
	"\x06system\x18\x01 \x01(\tR\x06system\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\rR\agroupId\x12\x1b\n" +
	"\tsource_id\x18\x04 \x01(\rR\bsourceId\x12!\n" +
	"\ffrequency_hz\x18\x05 \x01(\rR\vfrequencyHz\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x06 \x01(\rR\tchannelId\x12%\n" +
	"\x0echannel_number\x18\a \x01(\rR\rchannelNumber\x12\x1c\n" +
	"\tencrypted\x18\b \x01(\bR\tencrypted\x12\x1c\n" +
	"\temergency\x18\t \x01(\bR\temergency\x12\x1b\n" +
	"\tdata_call\x18\n" +
	" \x01(\bR\bdataCall\x12!\n" +
	"\falgorithm_id\x18\v \x01(\rR\valgorithmId\x12\x15\n" +
	"\x06key_id\x18\f \x01(\rR\x05keyId\"\x96\x01\n" +
	"\tCallStart\x12+\n" +
	"\x05grant\x18\x01 \x01(\v2\x15.gophertrunk.v1.GrantR\x05grant\x127\n" +
	"\ttalkgroup\x18\x02 \x01(\v2\x19.gophertrunk.v1.TalkGroupR\ttalkgroup\x12#\n" +
	"\rdevice_serial\x18\x03 \x01(\tR\fdeviceSerial\"\xe6\x01\n" +
	"\aCallEnd\x12+\n" +
	"\x05grant\x18\x01 \x01(\v2\x15.gophertrunk.v1.GrantR\x05grant\x127\n" +
	"\ttalkgroup\x18\x02 \x01(\v2\x19.gophertrunk.v1.TalkGroupR\ttalkgroup\x12#\n" +
	"\rdevice_serial\x18\x03 \x01(\tR\fdeviceSerial\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\tR\tstartedAt\x12\x19\n" +
	"\bended_at\x18\x05 \x01(\tR\aendedAt\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\"k\n" +
	"\tSDRStatus\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\tR\x06serial\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x1a\n" +
	"\battached\x18\x04 \x01(\bR\battached\">\n" +
	"\n" +
	"ErrorEvent\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xcc\x01\n" +
	"\tTalkGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1b\n" +
	"\talpha_tag\x18\x02 \x01(\tR\balphaTag\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x10\n" +
	"\x03tag\x18\x04 \x01(\tR\x03tag\x12\x14\n" +
	"\x05group\x18\x05 \x01(\tR\x05group\x12\x12\n" +
	"\x04mode\x18\x06 \x01(\tR\x04mode\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\x12\x18\n" +
	"\alockout\x18\b \x01(\bR\alockoutB>Z<github.com/MattCheramie/GopherTrunk/internal/api/pb/v1;apiv1b\x06proto3"

var (
	file_events_proto_rawDescOnce sync.Once
	file_events_proto_rawDescData []byte
)

func file_events_proto_rawDescGZIP() []byte {
	file_events_proto_rawDescOnce.Do(func() {
		file_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)))
	})
	return file_events_proto_rawDescData
}

var file_events_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_events_proto_goTypes = []any{
	(*Event)(nil),      // 0: gophertrunk.v1.Event
	(*CCLocked)(nil),   // 1: gophertrunk.v1.CCLocked
	(*CCLost)(nil),     // 2: gophertrunk.v1.CCLost
	(*Grant)(nil),      // 3: gophertrunk.v1.Grant
	(*CallStart)(nil),  // 4: gophertrunk.v1.CallStart
	(*CallEnd)(nil),    // 5: gophertrunk.v1.CallEnd
	(*SDRStatus)(nil),  // 6: gophertrunk.v1.SDRStatus
	(*ErrorEvent)(nil), // 7: gophertrunk.v1.ErrorEvent
	(*TalkGroup)(nil),  // 8: gophertrunk.v1.TalkGroup
	nil,                // 9: gophertrunk.v1.CCLocked.AttrsEntry
	nil,                // 10: gophertrunk.v1.CCLost.AttrsEntry
}
var file_events_proto_depIdxs = []int32{
	1,  // 0: gophertrunk.v1.Event.cc_locked:type_name -> gophertrunk.v1.CCLocked
	2,  // 1: gophertrunk.v1.Event.cc_lost:type_name -> gophertrunk.v1.CCLost
	3,  // 2: gophertrunk.v1.Event.grant:type_name -> gophertrunk.v1.Grant
	4,  // 3: gophertrunk.v1.Event.call_start:type_name -> gophertrunk.v1.CallStart
	5,  // 4: gophertrunk.v1.Event.call_end:type_name -> gophertrunk.v1.CallEnd
	6,  // 5: gophertrunk.v1.Event.sdr_status:type_name -> gophertrunk.v1.SDRStatus
	7,  // 6: gophertrunk.v1.Event.error:type_name -> gophertrunk.v1.ErrorEvent
	9,  // 7: gophertrunk.v1.CCLocked.attrs:type_name -> gophertrunk.v1.CCLocked.AttrsEntry
	10, // 8: gophertrunk.v1.CCLost.attrs:type_name -> gophertrunk.v1.CCLost.AttrsEntry
	3,  // 9: gophertrunk.v1.CallStart.grant:type_name -> gophertrunk.v1.Grant
	8,  // 10: gophertrunk.v1.CallStart.talkgroup:type_name -> gophertrunk.v1.TalkGroup
	3,  // 11: gophertrunk.v1.CallEnd.grant:type_name -> gophertrunk.v1.Grant
	8,  // 12: gophertrunk.v1.CallEnd.talkgroup:type_name -> gophertrunk.v1.TalkGroup
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_events_proto_init() }
func file_events_proto_init() {
	if File_events_proto != nil {
		return
	}
	file_events_proto_msgTypes[0].OneofWrappers = []any{
		(*Event_CcLocked)(nil),
		(*Event_CcLost)(nil),
		(*Event_Grant)(nil),
		(*Event_CallStart)(nil),
		(*Event_CallEnd)(nil),
		(*Event_SdrStatus)(nil),
		(*Event_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_proto_goTypes,
		DependencyIndexes: file_events_proto_depIdxs,
		MessageInfos:      file_events_proto_msgTypes,
	}.Build()
	File_events_proto = out.File
	file_events_proto_goTypes = nil
	file_events_proto_depIdxs = nil
}
