// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: rid.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RID is the per-radio-unit (subscriber unit) identifier as exposed by
// /api/v1/rids — the operator-configured static catalogue merged with
// the affiliation tracker's live observation. Configured rows carry
// alias / tag / owner / etc. from the per-system rid_alias_file; live
// rows carry the over-the-air observation overlay.
type RID struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Alias       string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Tag         string                 `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	Group       string                 `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty"`
	Owner       string                 `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	Priority    uint32                 `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	Lockout     bool                   `protobuf:"varint,8,opt,name=lockout,proto3" json:"lockout,omitempty"`
	Watch       bool                   `protobuf:"varint,9,opt,name=watch,proto3" json:"watch,omitempty"`
	Icon        string                 `protobuf:"bytes,10,opt,name=icon,proto3" json:"icon,omitempty"`
	// Configured is true when the row is backed by an rid_alias_file
	// entry; false for radios only ever seen over the air.
	Configured bool `protobuf:"varint,11,opt,name=configured,proto3" json:"configured,omitempty"`
	// Live observation overlay — empty/zero when the RID has not been
	// observed since the daemon started (or since the tracker swept it).
	System        string `protobuf:"bytes,12,opt,name=system,proto3" json:"system,omitempty"`
	Protocol      string `protobuf:"bytes,13,opt,name=protocol,proto3" json:"protocol,omitempty"`
	LastTalkgroup uint32 `protobuf:"varint,14,opt,name=last_talkgroup,json=lastTalkgroup,proto3" json:"last_talkgroup,omitempty"`
	TalkerAlias   string `protobuf:"bytes,15,opt,name=talker_alias,json=talkerAlias,proto3" json:"talker_alias,omitempty"`
	TalkerAliasAt string `protobuf:"bytes,16,opt,name=talker_alias_at,json=talkerAliasAt,proto3" json:"talker_alias_at,omitempty"` // RFC3339
	CallCount     uint64 `protobuf:"varint,17,opt,name=call_count,json=callCount,proto3" json:"call_count,omitempty"`
	FirstSeen     string `protobuf:"bytes,18,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"` // RFC3339
	LastSeen      string `protobuf:"bytes,19,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`    // RFC3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RID) Reset() {
	*x = RID{}
	mi := &file_rid_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RID) ProtoMessage() {}

func (x *RID) ProtoReflect() protoreflect.Message {
	mi := &file_rid_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RID.ProtoReflect.Descriptor instead.
func (*RID) Descriptor() ([]byte, []int) {
	return file_rid_proto_rawDescGZIP(), []int{0}
}

func (x *RID) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RID) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *RID) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RID) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *RID) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *RID) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *RID) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *RID) GetLockout() bool {
	if x != nil {
		return x.Lockout
	}
	return false
}

func (x *RID) GetWatch() bool {
	if x != nil {
		return x.Watch
	}
	return false
}

func (x *RID) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *RID) GetConfigured() bool {
	if x != nil {
		return x.Configured
	}
	return false
}

func (x *RID) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

func (x *RID) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *RID) GetLastTalkgroup() uint32 {
	if x != nil {
		return x.LastTalkgroup
	}
	return 0
}

func (x *RID) GetTalkerAlias() string {
	if x != nil {
		return x.TalkerAlias
	}
	return ""
}

func (x *RID) GetTalkerAliasAt() string {
	if x != nil {
		return x.TalkerAliasAt
	}
	return ""
}

func (x *RID) GetCallCount() uint64 {
	if x != nil {
		return x.CallCount
	}
	return 0
}

func (x *RID) GetFirstSeen() string {
	if x != nil {
		return x.FirstSeen
	}
	return ""
}

func (x *RID) GetLastSeen() string {
	if x != nil {
		return x.LastSeen
	}
	return ""
}

type ListRIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRIDsRequest) Reset() {
	*x = ListRIDsRequest{}
	mi := &file_rid_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRIDsRequest) ProtoMessage() {}

func (x *ListRIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rid_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRIDsRequest.ProtoReflect.Descriptor instead.
func (*ListRIDsRequest) Descriptor() ([]byte, []int) {
	return file_rid_proto_rawDescGZIP(), []int{1}
}

type ListRIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rids          []*RID                 `protobuf:"bytes,1,rep,name=rids,proto3" json:"rids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRIDsResponse) Reset() {
	*x = ListRIDsResponse{}
	mi := &file_rid_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRIDsResponse) ProtoMessage() {}

func (x *ListRIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rid_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRIDsResponse.ProtoReflect.Descriptor instead.
func (*ListRIDsResponse) Descriptor() ([]byte, []int) {
	return file_rid_proto_rawDescGZIP(), []int{2}
}

func (x *ListRIDsResponse) GetRids() []*RID {
	if x != nil {
		return x.Rids
	}
	return nil
}

type GetRIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRIDRequest) Reset() {
	*x = GetRIDRequest{}
	mi := &file_rid_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRIDRequest) ProtoMessage() {}

func (x *GetRIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rid_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRIDRequest.ProtoReflect.Descriptor instead.
func (*GetRIDRequest) Descriptor() ([]byte, []int) {
	return file_rid_proto_rawDescGZIP(), []int{3}
}

func (x *GetRIDRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetRIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rid           *RID                   `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRIDResponse) Reset() {
	*x = GetRIDResponse{}
	mi := &file_rid_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRIDResponse) ProtoMessage() {}

func (x *GetRIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rid_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRIDResponse.ProtoReflect.Descriptor instead.
func (*GetRIDResponse) Descriptor() ([]byte, []int) {
	return file_rid_proto_rawDescGZIP(), []int{4}
}

func (x *GetRIDResponse) GetRid() *RID {
	if x != nil {
		return x.Rid
	}
	return nil
}

type ListRIDHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`  // 0 = server default
	System        string                 `protobuf:"bytes,3,opt,name=system,proto3" json:"system,omitempty"` // optional system filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRIDHistoryRequest) Reset() {
	*x = ListRIDHistoryRequest{}
	mi := &file_rid_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRIDHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRIDHistoryRequest) ProtoMessage() {}

func (x *ListRIDHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rid_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRIDHistoryRequest.ProtoReflect.Descriptor instead.
func (*ListRIDHistoryRequest) Descriptor() ([]byte, []int) {
	return file_rid_proto_rawDescGZIP(), []int{5}
}

func (x *ListRIDHistoryRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListRIDHistoryRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRIDHistoryRequest) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

type RIDCallRow struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	System         string                 `protobuf:"bytes,2,opt,name=system,proto3" json:"system,omitempty"`
	Protocol       string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	GroupId        uint32                 `protobuf:"varint,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	SourceId       uint32                 `protobuf:"varint,5,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	FrequencyHz    uint32                 `protobuf:"varint,6,opt,name=frequency_hz,json=frequencyHz,proto3" json:"frequency_hz,omitempty"`
	Encrypted      bool                   `protobuf:"varint,7,opt,name=encrypted,proto3" json:"encrypted,omitempty"`
	Emergency      bool                   `protobuf:"varint,8,opt,name=emergency,proto3" json:"emergency,omitempty"`
	DataCall       bool                   `protobuf:"varint,9,opt,name=data_call,json=dataCall,proto3" json:"data_call,omitempty"`
	DeviceSerial   string                 `protobuf:"bytes,10,opt,name=device_serial,json=deviceSerial,proto3" json:"device_serial,omitempty"`
	StartedAt      string                 `protobuf:"bytes,11,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"` // RFC3339
	EndedAt        string                 `protobuf:"bytes,12,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`       // RFC3339, empty if still active
	DurationMs     int64                  `protobuf:"varint,13,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	EndReason      string                 `protobuf:"bytes,14,opt,name=end_reason,json=endReason,proto3" json:"end_reason,omitempty"`
	TalkgroupAlpha string                 `protobuf:"bytes,15,opt,name=talkgroup_alpha,json=talkgroupAlpha,proto3" json:"talkgroup_alpha,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RIDCallRow) Reset() {
	*x = RIDCallRow{}
	mi := &file_rid_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RIDCallRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RIDCallRow) ProtoMessage() {}

func (x *RIDCallRow) ProtoReflect() protoreflect.Message {
	mi := &file_rid_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RIDCallRow.ProtoReflect.Descriptor instead.
func (*RIDCallRow) Descriptor() ([]byte, []int) {
	return file_rid_proto_rawDescGZIP(), []int{6}
}

func (x *RIDCallRow) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RIDCallRow) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

func (x *RIDCallRow) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *RIDCallRow) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *RIDCallRow) GetSourceId() uint32 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

func (x *RIDCallRow) GetFrequencyHz() uint32 {
	if x != nil {
		return x.FrequencyHz
	}
	return 0
}

func (x *RIDCallRow) GetEncrypted() bool {
	if x != nil {
		return x.Encrypted
	}
	return false
}

func (x *RIDCallRow) GetEmergency() bool {
	if x != nil {
		return x.Emergency
	}
	return false
}

func (x *RIDCallRow) GetDataCall() bool {
	if x != nil {
		return x.DataCall
	}
	return false
}

func (x *RIDCallRow) GetDeviceSerial() string {
	if x != nil {
		return x.DeviceSerial
	}
	return ""
}

func (x *RIDCallRow) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *RIDCallRow) GetEndedAt() string {
	if x != nil {
		return x.EndedAt
	}
	return ""
}

func (x *RIDCallRow) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *RIDCallRow) GetEndReason() string {
	if x != nil {
		return x.EndReason
	}
	return ""
}

func (x *RIDCallRow) GetTalkgroupAlpha() string {
	if x != nil {
		return x.TalkgroupAlpha
	}
	return ""
}

type ListRIDHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Calls         []*RIDCallRow          `protobuf:"bytes,1,rep,name=calls,proto3" json:"calls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRIDHistoryResponse) Reset() {
	*x = ListRIDHistoryResponse{}
	mi := &file_rid_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRIDHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRIDHistoryResponse) ProtoMessage() {}

func (x *ListRIDHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rid_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRIDHistoryResponse.ProtoReflect.Descriptor instead.
func (*ListRIDHistoryResponse) Descriptor() ([]byte, []int) {
	return file_rid_proto_rawDescGZIP(), []int{7}
}

func (x *ListRIDHistoryResponse) GetCalls() []*RIDCallRow {
	if x != nil {
		return x.Calls
	}
	return nil
}

var File_rid_proto protoreflect.FileDescriptor

const file_rid_proto_rawDesc = "" +
	"\n" +
	"\trid.proto\x12\x0egophertrunk.v1\"\x8c\x04\n" +
	"\x03RID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x10\n" +
	"\x03tag\x18\x04 \x01(\tR\x03tag\x12\x14\n" +
	"\x05group\x18\x05 \x01(\tR\x05group\x12\x14\n" +
	"\x05owner\x18\x06 \x01(\tR\x05owner\x12\x1a\n" +
	"\bpriority\x18\a \x01(\rR\bpriority\x12\x18\n" +
	"\alockout\x18\b \x01(\bR\alockout\x12\x14\n" +
	"\x05watch\x18\t \x01(\bR\x05watch\x12\x12\n" +
	"\x04icon\x18\n" +
	" \x01(\tR\x04icon\x12\x1e\n" +
	"\n" +
	"configured\x18\v \x01(\bR\n" +
	"configured\x12\x16\n" +
	"\x06system\x18\f \x01(\tR\x06system\x12\x1a\n" +
	"\bprotocol\x18\r \x01(\tR\bprotocol\x12%\n" +
	"\x0elast_talkgroup\x18\x0e \x01(\rR\rlastTalkgroup\x12!\n" +
	"\ftalker_alias\x18\x0f \x01(\tR\vtalkerAlias\x12&\n" +
	"\x0ftalker_alias_at\x18\x10 \x01(\tR\rtalkerAliasAt\x12\x1d\n" +
	"\n" +
	"call_count\x18\x11 \x01(\x04R\tcallCount\x12\x1d\n" +
	"\n" +
	"first_seen\x18\x12 \x01(\tR\tfirstSeen\x12\x1b\n" +
	"\tlast_seen\x18\x13 \x01(\tR\blastSeen\"\x11\n" +
	"\x0fListRIDsRequest\";\n" +
	"\x10ListRIDsResponse\x12'\n" +
	"\x04rids\x18\x01 \x03(\v2\x13.gophertrunk.v1.RIDR\x04rids\"\x1f\n" +
	"\rGetRIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"7\n" +
	"\x0eGetRIDResponse\x12%\n" +
	"\x03rid\x18\x01 \x01(\v2\x13.gophertrunk.v1.RIDR\x03rid\"U\n" +
	"\x15ListRIDHistoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x16\n" +
	"\x06system\x18\x03 \x01(\tR\x06system\"\xcc\x03\n" +
	"\n" +
	"RIDCallRow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06system\x18\x02 \x01(\tR\x06system\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x19\n" +
	"\bgroup_id\x18\x04 \x01(\rR\agroupId\x12\x1b\n" +
	"\tsource_id\x18\x05 \x01(\rR\bsourceId\x12!\n" +
	"\ffrequency_hz\x18\x06 \x01(\rR\vfrequencyHz\x12\x1c\n" +
	"\tencrypted\x18\a \x01(\bR\tencrypted\x12\x1c\n" +
	"\temergency\x18\b \x01(\bR\temergency\x12\x1b\n" +
	"\tdata_call\x18\t \x01(\bR\bdataCall\x12#\n" +
	"\rdevice_serial\x18\n" +
	" \x01(\tR\fdeviceSerial\x12\x1d\n" +
	"\n" +
	"started_at\x18\v \x01(\tR\tstartedAt\x12\x19\n" +
	"\bended_at\x18\f \x01(\tR\aendedAt\x12\x1f\n" +
	"\vduration_ms\x18\r \x01(\x03R\n" +
	"durationMs\x12\x1d\n" +
	"\n" +
	"end_reason\x18\x0e \x01(\tR\tendReason\x12'\n" +
	"\x0ftalkgroup_alpha\x18\x0f \x01(\tR\x0etalkgroupAlpha\"J\n" +
	"\x16ListRIDHistoryResponse\x120\n" +
	"\x05calls\x18\x01 \x03(\v2\x1a.gophertrunk.v1.RIDCallRowR\x05calls2\x85\x02\n" +
	"\n" +
	"RIDService\x12M\n" +
	"\bListRIDs\x12\x1f.gophertrunk.v1.ListRIDsRequest\x1a .gophertrunk.v1.ListRIDsResponse\x12G\n" +
	"\x06GetRID\x12\x1d.gophertrunk.v1.GetRIDRequest\x1a\x1e.gophertrunk.v1.GetRIDResponse\x12_\n" +
	"\x0eListRIDHistory\x12%.gophertrunk.v1.ListRIDHistoryRequest\x1a&.gophertrunk.v1.ListRIDHistoryResponseB>Z<github.com/MattCheramie/GopherTrunk/internal/api/pb/v1;apiv1b\x06proto3"

var (
	file_rid_proto_rawDescOnce sync.Once
	file_rid_proto_rawDescData []byte
)

func file_rid_proto_rawDescGZIP() []byte {
	file_rid_proto_rawDescOnce.Do(func() {
		file_rid_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rid_proto_rawDesc), len(file_rid_proto_rawDesc)))
	})
	return file_rid_proto_rawDescData
}

var file_rid_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_rid_proto_goTypes = []any{
	(*RID)(nil),                    // 0: gophertrunk.v1.RID
	(*ListRIDsRequest)(nil),        // 1: gophertrunk.v1.ListRIDsRequest
	(*ListRIDsResponse)(nil),       // 2: gophertrunk.v1.ListRIDsResponse
	(*GetRIDRequest)(nil),          // 3: gophertrunk.v1.GetRIDRequest
	(*GetRIDResponse)(nil),         // 4: gophertrunk.v1.GetRIDResponse
	(*ListRIDHistoryRequest)(nil),  // 5: gophertrunk.v1.ListRIDHistoryRequest
	(*RIDCallRow)(nil),             // 6: gophertrunk.v1.RIDCallRow
	(*ListRIDHistoryResponse)(nil), // 7: gophertrunk.v1.ListRIDHistoryResponse
}
var file_rid_proto_depIdxs = []int32{
	0, // 0: gophertrunk.v1.ListRIDsResponse.rids:type_name -> gophertrunk.v1.RID
	0, // 1: gophertrunk.v1.GetRIDResponse.rid:type_name -> gophertrunk.v1.RID
	6, // 2: gophertrunk.v1.ListRIDHistoryResponse.calls:type_name -> gophertrunk.v1.RIDCallRow
	1, // 3: gophertrunk.v1.RIDService.ListRIDs:input_type -> gophertrunk.v1.ListRIDsRequest
	3, // 4: gophertrunk.v1.RIDService.GetRID:input_type -> gophertrunk.v1.GetRIDRequest
	5, // 5: gophertrunk.v1.RIDService.ListRIDHistory:input_type -> gophertrunk.v1.ListRIDHistoryRequest
	2, // 6: gophertrunk.v1.RIDService.ListRIDs:output_type -> gophertrunk.v1.ListRIDsResponse
	4, // 7: gophertrunk.v1.RIDService.GetRID:output_type -> gophertrunk.v1.GetRIDResponse
	7, // 8: gophertrunk.v1.RIDService.ListRIDHistory:output_type -> gophertrunk.v1.ListRIDHistoryResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rid_proto_init() }
func file_rid_proto_init() {
	if File_rid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rid_proto_rawDesc), len(file_rid_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rid_proto_goTypes,
		DependencyIndexes: file_rid_proto_depIdxs,
		MessageInfos:      file_rid_proto_msgTypes,
	}.Build()
	File_rid_proto = out.File
	file_rid_proto_goTypes = nil
	file_rid_proto_depIdxs = nil
}
