// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: rid.proto

package apiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RIDService_ListRIDs_FullMethodName       = "/gophertrunk.v1.RIDService/ListRIDs"
	RIDService_GetRID_FullMethodName         = "/gophertrunk.v1.RIDService/GetRID"
	RIDService_ListRIDHistory_FullMethodName = "/gophertrunk.v1.RIDService/ListRIDHistory"
)

// RIDServiceClient is the client API for RIDService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RIDServiceClient interface {
	ListRIDs(ctx context.Context, in *ListRIDsRequest, opts ...grpc.CallOption) (*ListRIDsResponse, error)
	GetRID(ctx context.Context, in *GetRIDRequest, opts ...grpc.CallOption) (*GetRIDResponse, error)
	ListRIDHistory(ctx context.Context, in *ListRIDHistoryRequest, opts ...grpc.CallOption) (*ListRIDHistoryResponse, error)
}

type rIDServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRIDServiceClient(cc grpc.ClientConnInterface) RIDServiceClient {
	return &rIDServiceClient{cc}
}

func (c *rIDServiceClient) ListRIDs(ctx context.Context, in *ListRIDsRequest, opts ...grpc.CallOption) (*ListRIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRIDsResponse)
	err := c.cc.Invoke(ctx, RIDService_ListRIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rIDServiceClient) GetRID(ctx context.Context, in *GetRIDRequest, opts ...grpc.CallOption) (*GetRIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRIDResponse)
	err := c.cc.Invoke(ctx, RIDService_GetRID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rIDServiceClient) ListRIDHistory(ctx context.Context, in *ListRIDHistoryRequest, opts ...grpc.CallOption) (*ListRIDHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRIDHistoryResponse)
	err := c.cc.Invoke(ctx, RIDService_ListRIDHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RIDServiceServer is the server API for RIDService service.
// All implementations must embed UnimplementedRIDServiceServer
// for forward compatibility.
type RIDServiceServer interface {
	ListRIDs(context.Context, *ListRIDsRequest) (*ListRIDsResponse, error)
	GetRID(context.Context, *GetRIDRequest) (*GetRIDResponse, error)
	ListRIDHistory(context.Context, *ListRIDHistoryRequest) (*ListRIDHistoryResponse, error)
	mustEmbedUnimplementedRIDServiceServer()
}

// UnimplementedRIDServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRIDServiceServer struct{}

func (UnimplementedRIDServiceServer) ListRIDs(context.Context, *ListRIDsRequest) (*ListRIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRIDs not implemented")
}
func (UnimplementedRIDServiceServer) GetRID(context.Context, *GetRIDRequest) (*GetRIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRID not implemented")
}
func (UnimplementedRIDServiceServer) ListRIDHistory(context.Context, *ListRIDHistoryRequest) (*ListRIDHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRIDHistory not implemented")
}
func (UnimplementedRIDServiceServer) mustEmbedUnimplementedRIDServiceServer() {}
func (UnimplementedRIDServiceServer) testEmbeddedByValue()                    {}

// UnsafeRIDServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RIDServiceServer will
// result in compilation errors.
type UnsafeRIDServiceServer interface {
	mustEmbedUnimplementedRIDServiceServer()
}

func RegisterRIDServiceServer(s grpc.ServiceRegistrar, srv RIDServiceServer) {
	// If the following call panics, it indicates UnimplementedRIDServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RIDService_ServiceDesc, srv)
}

func _RIDService_ListRIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RIDServiceServer).ListRIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RIDService_ListRIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RIDServiceServer).ListRIDs(ctx, req.(*ListRIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RIDService_GetRID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RIDServiceServer).GetRID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RIDService_GetRID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RIDServiceServer).GetRID(ctx, req.(*GetRIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RIDService_ListRIDHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRIDHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RIDServiceServer).ListRIDHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RIDService_ListRIDHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RIDServiceServer).ListRIDHistory(ctx, req.(*ListRIDHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RIDService_ServiceDesc is the grpc.ServiceDesc for RIDService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RIDService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gophertrunk.v1.RIDService",
	HandlerType: (*RIDServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRIDs",
			Handler:    _RIDService_ListRIDs_Handler,
		},
		{
			MethodName: "GetRID",
			Handler:    _RIDService_GetRID_Handler,
		},
		{
			MethodName: "ListRIDHistory",
			Handler:    _RIDService_ListRIDHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rid.proto",
}
